name: haihelper
description: A new Flutter project

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  # Remove or comment out the fonts section for now
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  image_picker: ^1.0.7
  country_picker: ^2.0.27
  slide_to_act: ^2.0.1
  shared_preferences: ^2.5.2
  fl_chart: ^0.70.2
  flutter_screenutil: ^5.9.3

